spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cpmsdb
    username: root
    password: Chathuka@9911

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

jwt:
  secret: cpms-secure-jwt-secret-key-2026-production-very-strong-key-64bytes
  expiration: 86400000