spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cpmsdb
    username: root
    password: pass123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

jwt:
  secret: cpms-secure-jwt-secret-key-2026-production-very-strong-key-64bytes
  expiration: 86400000


payhere:
  merchantId: "1233614"
  merchantSecret: "NDE0OTYyNjgxMTkwMjY3Njg2NTIyMDE0ODkxMDUyMzIwOTA1NjM0"
  returnUrl: "http://localhost:5173/customer/payments"
  cancelUrl: "http://localhost:5173/customer/payments"
  notifyUrl: "http://localhost:8080/api/payments/payhere/notify"